### ISSUE TITLE
about accuracy?

### ISSUE THREAD

**Issue by HITerStudy** [pavlo-melnyk/offline-HCCR#2]
Hello, Why I cannot get the accuracy proposed in the paper, although I performed the experiment according to the guides same as that of paper? Please give me some instructions if possible?Thanks a lot!

**Comment by pavlo-melnyk** [comment]
If you use the same architecture and training strategy (described in Section 4.2) as we used in our experiments, you should be able to obtain a comparable final score on the benchmark. A minor difference might occur due to the different data preprocessing, so make sure you take this into account.
