### ISSUE TITLE
Implementing on different dataset?

### ISSUE THREAD

**Issue by iampartho** [pavlo-melnyk/offline-HCCR#3]
Hey there thank you for this repository, I was wondering if it's possible to use your code to train the network for different dataset (like in a different language character recognition task)? If that is possible then which code and also which part of the code should I be looking for could you please specify? Thank you.

**Comment by pavlo-melnyk** [comment]
Hi, 

Yes, it is possible to use the code to train the network on a different dataset. 
You might want to use the [melnyk_net.py](https://github.com/pavlo-melnyk/offline-HCCR/blob/master/src/melnyk_net.py) file: 

- change the arguments passed to the `melnyk_net` function in line 146 
(e.g., `input_shape=[your_data_sample_shape]`, `num_classes=[your_data_num_classes]`, etc.);
- define training and validation/test sets in line 178 and uncomment the following lines.

The training procedure can be changed by modifying the code in lines 149-175.
